### ISSUE TITLE
Am having an issue when deploying ARI 

### ISSUE THREAD

**Issue by navneethvs1985** [microsoft/ARI#164]
First of all thanks to the devs for creating this amazing script. I have tried to deploy the ARI script into automation. But get the below errors when I try to run it. Please let me know if you can help me. 

InvalidOperation: C:\usr\src\PSModules\ImportExcel\Public\Set-ExcelRange.ps1:107 Line | 107 | … $Range.Style.HorizontalAlignment = $HorizontalAlignment | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | The property 'HorizontalAlignment' cannot be found on this object. Verify that the property exists and can be set.

InvalidOperation: C:\usr\src\PSModules\ImportExcel\Public\Set-ExcelRange.ps1:128 Line | 128 | … $Range.Style.Numberformat.Format = (Expand-NumberFormat $ … | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | The property 'Format' cannot be found on this object. Verify that the property exists and can be set.

InvalidOperation: Line | 134 | $User = $Subscriptions[0].user.name | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | Cannot index into a null array.

System.Management.Automation.RuntimeException: The property 'HorizontalAlignment' cannot be found on this object. Verify that the property exists and can be set.
   at CallSite.Target(Closure , CallSite , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
System.Management.Automation.RuntimeException: The property 'Format' cannot be found on this object. Verify that the property exists and can be set.
   at CallSite.Target(Closure , CallSite , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Failed autosizing columns of worksheet 'Subscriptions': You cannot call a method on a null-valued expression.
System.Management.Automation.RuntimeException: Cannot index into a null array.
   at CallSite.Target(Closure , CallSite , Object , Int32 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Failed adding PivotTable 'P1': Index operation failed; the array index evaluated to null.
Failed adding chart for pivotable 'P1': Cannot bind argument to parameter 'PivotTable' because it is null.
Failed adding PivotTable 'P3': Cannot index into a null array.
Failed adding chart for pivotable 'P3': Cannot bind argument to parameter 'PivotTable' because it is null.
Failed adding PivotTable 'P4': Cannot index into a null array.
Failed adding chart for pivotable 'P4': Cannot bind argument to parameter 'PivotTable' because it is null.
Failed adding PivotTable 'P6': Index operation failed; the array index evaluated to null.
Failed adding chart for pivotable 'P6': Cannot bind argument to parameter 'PivotTable' because it is null.

**Comment by navneethvs1985** [comment]
I fixed it by reading previous issues.
