### ISSUE TITLE
"The property 'HorizontalAlignment' cannot be found on this object. Verify that the property exists and can be set." in playbook output

### ISSUE THREAD

**Issue by nestersan-ja** [microsoft/ARI#240]
I'm using latest instructions on the Automation ARI setup:
Invoke-ARI -TenantId  'xxxxxxx-xxx-xxxxx-xxxxxxxxxxxx' -Automation -SkipDiagram -SkipAPIs -StorageAccount 'xxxxx' -StorageContainer 'xxxxx'

Running Inventory Jobs
Azure Inventory
Azure Resource Inventory Subscriptions
Adding worksheet 'Subscriptions'.
Defined table 'SubsTable_0' at A1:A1
Auto-sized columns
System.Management.Automation.RuntimeException: The property 'HorizontalAlignment' cannot be found on this object. Verify that the property exists and can be set.
   at CallSite.Target(Closure, CallSite, Object, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
System.Management.Automation.RuntimeException: The property 'Format' cannot be found on this object. Verify that the property exists and can be set.
   at CallSite.Target(Closure, CallSite, Object, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Failed autosizing columns of worksheet 'Subscriptions': You cannot call a method on a null-valued expression.
Saved workbook C:\app\ARI_Automation_Report_2024-12-10_18_30.xlsx

![Image](https://github.com/user-attachments/assets/ea55f2ee-4cd7-430c-a546-962b4cb49255)

**Comment by Claudio-Merola** [comment]
Hello,

That error might occur when some type of resource does not exist in the environment and the script tries to create a spreadsheet for it, like Policies, Advisories, Security Center and etc.

The Excel is being created?
